### ISSUE TITLE
failed to Activate package environment (Rmath)

### ISSUE THREAD

**Issue by XiaoyuZeng** [yjunechoe/jlmerclusterperm#5]
Hi,
Thanks for your time and effort to develop this package. 
## Problem
I'm new to this package, and faced with an environment setting problem.
After running jlmerclusterperm_setup(), I encountered an error:

> Starting Julia with 7 threads [3.2s]
> ┌ Warning: could not download https://pkg.julialang.org/registries
> │   exception = Downloads.RequestError("https://pkg.julialang.org/registries", 28, "Failed to connect to cn-northeast.pkg.juliacn.com port 443 after 21047 ms: Timed out", Downloads.Response("https", "https://cn-northeast.pkg.juliacn.com/registries", 301, "HTTP/1.1 301 CN northeast internal redirect trigger", ["connection" => "close", "content-length" => "0", "server" => "Varnish", "retry-after" => "0", "location" => "https://cn-northeast.pkg.juliacn.com/registries", "x-geo-continent" => "AS", "x-geo-country" => "CN", "x-geo-region" => "BJ", "accept-ranges" => "bytes", "date" => "Fri, 14 Jul 2023 04:20:32 GMT", "via" => "1.1 varnish", "x-served-by" => "cache-tyo11976-TYO", "x-cache" => "HIT", "x-cache-hits" => "0", "x-timer" => "S1689308433.892732,VS0,VE1"]))
> └ @ Pkg.Registry C:\Users\xiaoy\AppData\Local\Programs\JULIA-~1.2\share\julia\stdlib\v1.9\Pkg\src\Registry\Registry.jl:69
>     Updating registry at `C:\Users\xiaoy\.julia\registries\General`
>     Updating git-repo `https://github.com/JuliaRegistries/General.git`
> ┌ Error: Some registries failed to update:
> │     — C:\Users\xiaoy\.julia\registries\General — failed to fetch from repo: failed to fetch from https://github.com/JuliaRegistries/General.git, error: GitError(Code:ERROR, Class:OS, failed to send request: 操作超时
> │ )
> └ @ Pkg.Registry C:\Users\xiaoy\AppData\Local\Programs\JULIA-~1.2\share\julia\stdlib\v1.9\Pkg\src\Registry\Registry.jl:510
> ┌ Warning: could not download https://pkg.julialang.org/registries
> │   exception = Downloads.RequestError("https://pkg.julialang.org/registries", 28, "Failed to connect to cn-northeast.pkg.juliacn.com port 443 after 21039 ms: Timed out", Downloads.Response("https", "https://cn-northeast.pkg.juliacn.com/registries", 301, "HTTP/1.1 301 CN northeast internal redirect trigger", ["connection" => "close", "content-length" => "0", "server" => "Varnish", "retry-after" => "0", "location" => "https://cn-northeast.pkg.juliacn.com/registries", "x-geo-continent" => "AS", "x-geo-country" => "CN", "x-geo-region" => "BJ", "accept-ranges" => "bytes", "date" => "Fri, 14 Jul 2023 04:22:35 GMT", "via" => "1.1 varnish", "x-served-by" => "cache-tyo11971-TYO", "x-cache" => "HIT", "x-cache-hits" => "0", "x-timer" => "S1689308556.662519,VS0,VE0"]))
> └ @ Pkg.Registry C:\Users\xiaoy\AppData\Local\Programs\JULIA-~1.2\share\julia\stdlib\v1.9\Pkg\src\Registry\Registry.jl:69
>    Installed DiffRules ─────────────── v1.15.1
>    Installed Adapt ─────────────────── v3.6.2
>    Installed MatrixFactorizations ──── v2.0.0
>    Installed HypergeometricFunctions ─ v0.3.20
>    Installed BandedMatrices ────────── v0.17.30
>    Installed MutableArithmetics ────── v1.3.0
>    Installed Suppressor ────────────── v0.2.4
>    Installed Preferences ───────────── v1.4.0
>    Installed JSON3 ─────────────────── v1.13.1
>    Installed Arrow ─────────────────── v2.6.2
>    Installed Mocking ───────────────── v0.7.7
>    Installed FastGaussQuadrature ───── v0.5.1
>    Installed IfElse ────────────────── v0.1.1
>    Installed SentinelArrays ────────── v1.4.0
>    Installed Parsers ───────────────── v2.7.1
>    Installed SpecialFunctions ──────── v2.3.0
>    Installed ArrowTypes ────────────── v2.2.2
>    Installed TimeZones ─────────────── v1.10.0
>    Installed RecipesBase ───────────── v1.3.4
>    Installed BSplineKit ────────────── v0.16.2
>    Installed ConcurrentUtilities ───── v2.2.1
>    Installed StaticArraysCore ──────── v1.4.1
>    Installed StaticArrays ──────────── v1.6.1
>    Installed PrecompileTools ───────── v1.1.2
>    Installed EnumX ─────────────────── v1.0.4
>    Installed PrettyTables ──────────── v2.2.5
>    Installed Random123 ─────────────── v1.6.1
>    Installed TranscodingStreams ────── v0.9.13
>    Installed FillArrays ────────────── v1.4.0
>    Installed BitIntegers ───────────── v0.3.0
>    Installed StatsModels ───────────── v0.7.2
>    Installed MixedModels ───────────── v4.15.0
>    Installed LazyArrays ────────────── v1.2.2
>    Installed DataFrames ────────────── v1.6.0
>    Installed GLM ───────────────────── v1.8.3
>    Installed DataStructures ────────── v0.18.14
>    Installed Static ────────────────── v0.8.7
>    Installed LogExpFunctions ───────── v0.3.24
>    Installed CodecZlib ─────────────── v0.7.2
>    Installed Compat ────────────────── v4.7.0
>    Installed SortingAlgorithms ─────── v1.1.1
>    Installed ArrayLayouts ──────────── v1.0.11
>    Installed Distributions ─────────── v0.25.98
>    Installed MathOptInterface ──────── v1.18.0
> Error: Evaluation in Julia failed.
> Original Julia error message:
> LoadError: Unable to automatically download/install artifact 'Rmath' from sources listed in 'C:\Users\xiaoy\.julia\packages\Rmath_jll\JeAlY\Artifacts.toml'.
> Sources attempted:
> - https://pkg.julialang.org/artifact/abc0091a4956da8c501a50e1b1eba2735299c04e
>     Error: RequestError: HTTP/1.1 301 CN northeast internal redirect trigger (Failed to connect to cn-northeast.pkg.juliacn.com port 443 after 21057 ms: Timed out) while requesting https://pkg.julialang.org/artifact/abc0091a4956da8c501a50e1b1eba2735299c04e
> - https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.4.0+0/Rmath.v0.4.0.x86_64-w64-mingw32.tar.gz
>     Error: RequestError: Failed to connect to github.com port 443 after 21026 ms: Timed out while requesting https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.4.0+0/Rmath.v0.4.0.x86_64-w64-mingw32.tar.gz
> 
> Stacktrace:
>   [1] error(s::String)
>     @ Base .\error.jl:35
>   [2
> ✖ Activating package environment [8m 7s]
## Attempts
I've tried:
- reboot
- re-installed Julia
- re-installed jlmerclusterperm
but none of these attempts worked to install Rmath
is it just a network problem?
Any ideas to solve this problem?

**Comment by XiaoyuZeng** [comment]
I reset my network connection, it seems the problem has been solved~

> Show in New Window
> Warning: <anonymous>: ... may be used in an incorrect context: ‘.fun(piece, ...)’
> Warning: <anonymous>: ... may be used in an incorrect context: ‘.fun(piece, ...)’
> Saving 9.55 x 7.2 in image
> Show in New Window
> ✔ Starting Julia with 7 threads [3.3s]
> ┌ Warning: could not download https://pkg.julialang.org/registries
> │   exception = Downloads.RequestError("https://pkg.julialang.org/registries", 28, "Failed to connect to cn-northeast.pkg.juliacn.com port 443 after 21049 ms: Timed out", Downloads.Response("https", "https://cn-northeast.pkg.juliacn.com/registries", 301, "HTTP/1.1 301 CN northeast internal redirect trigger", ["connection" => "close", "content-length" => "0", "server" => "Varnish", "retry-after" => "0", "location" => "https://cn-northeast.pkg.juliacn.com/registries", "x-geo-continent" => "AS", "x-geo-country" => "CN", "x-geo-region" => "BJ", "accept-ranges" => "bytes", "date" => "Fri, 14 Jul 2023 04:45:36 GMT", "via" => "1.1 varnish", "x-served-by" => "cache-nrt-rjtf7700028-NRT", "x-cache" => "HIT", "x-cache-hits" => "0", "x-timer" => "S1689309936.076401,VS0,VE0"]))
> └ @ Pkg.Registry C:\Users\xiaoy\.julia\juliaup\julia-1.9.2+0.x64.w64.mingw32\share\julia\stdlib\v1.9\Pkg\src\Registry\Registry.jl:69
>     Updating registry at `C:\Users\xiaoy\.julia\registries\General`
>     Updating git-repo `https://github.com/JuliaRegistries/General.git`
>     Updating `D:\Program Files\R\R-4.3.1\library\jlmerclusterperm\julia\Project.toml`
>   [a93c6f00] + DataFrames v1.6.0
>   [38e38edf] + GLM v1.8.3
>   [ff71e718] + MixedModels v4.15.0
>   [92933f4c] + ProgressMeter v1.7.2
>   [74087812] + Random123 v1.6.1
> ⌃ [2913bbd2] + StatsBase v0.33.21
>   [3eaba693] + StatsModels v0.7.2
>   [fd094767] + Suppressor v0.2.4
>     Updating `D:\Program Files\R\R-4.3.1\library\jlmerclusterperm\julia\Manifest.toml`
>   [79e6a3ab] + Adapt v3.6.2
>   [4c555306] + ArrayLayouts v1.0.11
>   [69666777] + Arrow v2.6.2
>   [31f734f8] + ArrowTypes v2.2.2
>   [093aae92] + BSplineKit v0.16.2
>   [aae01518] + BandedMatrices v0.17.30
>   [6e4b80f9] + BenchmarkTools v1.3.2
>   [c3b6d118] + BitIntegers v0.3.0
>   [fa961155] + CEnum v0.4.2
>   [49dc2e85] + Calculus v0.5.1
>   [523fee87] + CodecBzip2 v0.7.2
>   [5ba52731] + CodecLz4 v0.4.0
>   [944b1d66] + CodecZlib v0.7.2
>   [6b39b394] + CodecZstd v0.7.2
>   [bbf7d656] + CommonSubexpressions v0.3.0
>   [34da2185] + Compat v4.7.0
>   [f0e56b4a] + ConcurrentUtilities v2.2.1
>   [a8cc5b0e] + Crayons v4.1.1
>   [9a962f9c] + DataAPI v1.15.0
>   [a93c6f00] + DataFrames v1.6.0
>   [864edb3b] + DataStructures v0.18.14
>   [e2d170a0] + DataValueInterfaces v1.0.0
>   [85a47980] + Dictionaries v0.3.25
>   [163ba53b] + DiffResults v1.1.0
>   [b552c78f] + DiffRules v1.15.1
>   [31c24e10] + Distributions v0.25.98
>   [ffbed154] + DocStringExtensions v0.9.3
>   [fa6b7ba4] + DualNumbers v0.6.8
>   [4e289a0a] + EnumX v1.0.4
>   [e2ba6199] + ExprTools v0.1.9
>   [442a2c76] + FastGaussQuadrature v0.5.1
>   [1a297f60] + FillArrays v1.4.0
>   [59287772] + Formatting v0.4.2
>   [f6369f11] + ForwardDiff v0.10.35
>   [38e38edf] + GLM v1.8.3
>   [34004b35] + HypergeometricFunctions v0.3.20
>   [615f187c] + IfElse v0.1.1
>   [313cdc1a] + Indexing v1.1.1
>   [842dd82b] + InlineStrings v1.4.0
>   [41ab1584] + InvertedIndices v1.3.0
>   [92d709cd] + IrrationalConstants v0.2.2
>   [82899510] + IteratorInterfaceExtensions v1.0.0
>   [692b3bcd] + JLLWrappers v1.4.1
>   [682c06a0] + JSON v0.21.4
>   [0f8b85d8] + JSON3 v1.13.1
>   [b964fa9f] + LaTeXStrings v1.3.0
>   [5078a376] + LazyArrays v1.2.2
>   [2ab3a3ac] + LogExpFunctions v0.3.24
>   [e6f89c97] + LoggingExtras v1.0.0
>   [1914dd2f] + MacroTools v0.5.10
>   [b8f27783] + MathOptInterface v1.18.0
>   [fdba3010] + MathProgBase v0.7.8
>   [a3b82374] + MatrixFactorizations v2.0.0
>   [e1d29d7a] + Missings v1.1.0
>   [ff71e718] + MixedModels v4.15.0
>   [78c3b35d] + Mocking v0.7.7
>   [d8a4904e] + MutableArithmetics v1.3.0
>   [76087f3c] + NLopt v0.6.5
>   [77ba4419] + NaNMath v1.0.2
>   [bac558e1] + OrderedCollections v1.6.0
>   [90014a1f] + PDMats v0.11.17
>   [69de0a69] + Parsers v2.7.1
>   [2dfb63ee] + PooledArrays v1.4.2
>   [aea7be01] + PrecompileTools v1.1.2
>   [21216c6a] + Preferences v1.4.0
>   [08abe8d2] + PrettyTables v2.2.5
>   [92933f4c] + ProgressMeter v1.7.2
>   [1fd47b50] + QuadGK v2.8.2
>   [74087812] + Random123 v1.6.1
>   [e6cf234a] + RandomNumbers v1.5.3
>   [3cdcf5f2] + RecipesBase v1.3.4
>   [189a3867] + Reexport v1.2.2
>   [ae029012] + Requires v1.3.0
>   [79098fc4] + Rmath v0.7.1
>   [6c6a2e73] + Scratch v1.2.0
>   [91c51154] + SentinelArrays v1.4.0
>   [1277b4bf] + ShiftedArrays v2.0.0
>   [a2af1166] + SortingAlgorithms v1.1.1
>   [276daf66] + SpecialFunctions v2.3.0
>   [03a91e81] + SplitApplyCombine v1.2.2
>   [aedffcd0] + Static v0.8.7
>   [90137ffa] + StaticArrays v1.6.1
>   [1e83bf80] + StaticArraysCore v1.4.1
>   [82ae8749] + StatsAPI v1.6.0
> ⌃ [2913bbd2] + StatsBase v0.33.21
>   [4c63d2b9] + StatsFuns v1.3.0
>   [3eaba693] + StatsModels v0.7.2
>   [892a3eda] + StringManipulation v0.3.0
>   [856f2bd8] + StructTypes v1.10.0
>   [fd094767] + Suppressor v0.2.4
>   [3783bdb8] + TableTraits v1.0.1
>   [bd369af6] + Tables v1.10.1
>   [f269a46b] + TimeZones v1.10.0
>   [3bb67fe8] + TranscodingStreams v0.9.13
>   [9d95f2ec] + TypedTables v1.4.3
>   [6e34b625] + Bzip2_jll v1.0.8+0
>   [5ced341a] + Lz4_jll v1.9.3+0
>   [079eb43e] + NLopt_jll v2.7.1+0
>   [efe28fd5] + OpenSpecFun_jll v0.5.5+0
>   [f50d1b31] + Rmath_jll v0.4.0+0
>   [3161d3a3] + Zstd_jll v1.5.5+0
>   [0dad84c5] + ArgTools v1.1.1
>   [56f22d72] + Artifacts
>   [2a0f44e3] + Base64
>   [ade2ca70] + Dates
>   [8ba89e20] + Distributed
>   [f43a241f] + Downloads v1.6.0
>   [7b1f6079] + FileWatching
>   [9fa8497b] + Future
>   [b77e0a4c] + InteractiveUtils
>   [4af54fe1] + LazyArtifacts
>   [b27032c2] + LibCURL v0.6.3
>   [76f85450] + LibGit2
>   [8f399da3] + Libdl
>   [37e2e46d] + LinearAlgebra
>   [56ddb016] + Logging
>   [d6f4376e] + Markdown
>   [a63ad114] + Mmap
>   [ca575930] + NetworkOptions v1.2.0
>   [44cfe95a] + Pkg v1.9.2
>   [de0858da] + Printf
>   [9abbd945] + Profile
>   [3fa0cd96] + REPL
>   [9a3f8284] + Random
>   [ea8e919c] + SHA v0.7.0
>   [9e88b42a] + Serialization
>   [6462fe0b] + Sockets
>   [2f01184e] + SparseArrays
>   [10745b16] + Statistics v1.9.0
>   [4607b0f0] + SuiteSparse
>   [fa267f1f] + TOML v1.0.3
>   [a4e569a6] + Tar v1.10.0
>   [8dfed614] + Test
>   [cf7118a7] + UUIDs
>   [4ec0a83e] + Unicode
>   [e66e0078] + CompilerSupportLibraries_jll v1.0.5+0
>   [deac9b47] + LibCURL_jll v7.84.0+0
>   [29816b5a] + LibSSH2_jll v1.10.2+0
>   [c8ffd9c3] + MbedTLS_jll v2.28.2+0
>   [14a3606d] + MozillaCACerts_jll v2022.10.11
>   [4536629a] + OpenBLAS_jll v0.3.21+4
>   [05823500] + OpenLibm_jll v0.8.1+0
>   [bea87d4a] + SuiteSparse_jll v5.10.1+6
>   [83775a58] + Zlib_jll v1.2.13+0
>   [8e850b90] + libblastrampoline_jll v5.8.0+0
>   [8e850ede] + nghttp2_jll v1.48.0+0
>   [3f19e933] + p7zip_jll v17.4.0+0
>         Info Packages marked with ⌃ have new versions available and may be upgradable.
> Precompiling project...
>   ✓ Suppressor
>   ✓ Compat
>   ✓ Calculus
>   ✓ MathProgBase
>   ✓ EnumX
>   ✓ LaTeXStrings
>   ✓ StructTypes
>   ✓ Requires
>   ✓ InvertedIndices
>   ✓ ArrowTypes
>   ✓ Reexport
>   ✓ SentinelArrays
>   ✓ DocStringExtensions
>   ✓ ExprTools
>   ✓ IfElse
>   ✓ StatsAPI
>   ✓ CompilerSupportLibraries_jll
>   ✓ BitIntegers
>   ✓ IrrationalConstants
>   ✓ ProgressMeter
>   ✓ Scratch
>   ✓ LoggingExtras
>   ✓ Indexing
>   ✓ Crayons
>   ✓ Formatting
>   ✓ CEnum
>   ✓ StaticArraysCore
>   ✓ ConcurrentUtilities
>   ✓ TranscodingStreams
>   ✓ MacroTools
>   ✓ Preferences
>   ✓ ShiftedArrays
>   ✓ StringManipulation
>   ✓ NaNMath
>   ✓ PDMats
>   ✓ Missings
>   ✓ PooledArrays
>   ✓ FillArrays
>   ✓ Compat → CompatLinearAlgebraExt
>   ✓ Adapt
>   ✓ Static
>   ✓ RandomNumbers
>   ✓ LogExpFunctions
>   ✓ DiffResults
>   ✓ Dictionaries
>   ✓ CodecZlib
>   ✓ CommonSubexpressions
>   ✓ PrecompileTools
>   ✓ JLLWrappers
>   ✓ MutableArithmetics
>   ✓ Mocking
>   ✓ DataStructures
>   ✓ Random123
>   ✓ SplitApplyCombine
>   ✓ ArrayLayouts
>   ✓ RecipesBase
>   ✓ Rmath_jll
>   ✓ StaticArrays
>   ✓ NLopt_jll
>   ✓ Zstd_jll
>   ✓ Bzip2_jll
>   ✓ Lz4_jll
>   ✓ SortingAlgorithms
>   ✓ OpenSpecFun_jll
>   ✓ QuadGK
>   ✓ TypedTables
>   ✓ MatrixFactorizations
>   ✓ Rmath
>   ✓ StaticArrays → StaticArraysStatisticsExt
>   ✓ Adapt → AdaptStaticArraysExt
>   ✓ CodecBzip2
>   ✓ CodecZstd
>   ✓ PrettyTables
>   ✓ CodecLz4
>   ✓ StatsBase
>   ✓ SpecialFunctions
>   ✓ LazyArrays
>   ✓ DualNumbers
>   ✓ DiffRules
>   ✓ FastGaussQuadrature
>   ✓ HypergeometricFunctions
>   ✓ StatsFuns
>   ✓ ForwardDiff
>   ✓ StatsModels
>   ✓ ForwardDiff → ForwardDiffStaticArraysExt
>   ✓ Distributions
>   ✓ Parsers
>   ✓ InlineStrings
>   ✓ GLM
>   ✓ JSON
>   ✓ BenchmarkTools
>   ✓ TimeZones
>   ✓ Arrow
>   ✓ JSON3
>   ✓ BandedMatrices
>   ✓ BSplineKit
>   ✓ DataFrames
>   ✓ MathOptInterface
>   ✓ NLopt
>   ✓ MixedModels
>   100 dependencies successfully precompiled in 283 seconds. 13 already precompiled.
>   1 dependency had warnings during precompilation:
> ┌ MixedModels [ff71e718-51f3-5ec2-a782-8ffcbfa3c316]
> │  Downloading artifact: TestData
> │   Downloading artifact: TestData
> └  
> ✔ Activating package environment [11m 16.6s]
> ✔ Running package setup scripts (15/15) [11.4s]

**Comment by yjunechoe** [comment]
Thanks for the report! Glad to hear that it was just a network issue (that's also what I suspected from the error messages).
